<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TeacherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $teachers = [
            [
                'avatar' => null,
                'prefix' => 'Mr.',
                'first_name' => 'Suman',
                'middle_name' => 'Kumar',
                'last_name' => 'Shrestha',
                'gender' => 'male',
                'date_of_birth' => '1980-05-15',
                'nid' => '1234567890',
                'contact' => '+9779812345678',
                'personal_email' => 'teacher1@example.com',
                'address' => 'Kathmandu',
                'city' => 'Kathmandu',
                'country' => 'Nepal',
                'postal_code' => '44600',
                'salary' => 50000.00,
                'joining_date' => '2010-08-01',
                
                'qualification' => 'M.Ed.',
                'user_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'avatar' => null,
                'prefix' => 'Ms.',
                'first_name' => 'Sita',
                'middle_name' => null,
                'last_name' => 'Gurung',
                'gender' => 'female',
                'date_of_birth' => '1985-02-20',
                'nid' => '0987654321',
                'contact' => '+9779801234567',
                'personal_email' => 'teacher2@example.com',
                'address' => 'Pokhara',
                'city' => 'Pokhara',
                'country' => 'Nepal',
                'postal_code' => '33700',
                'salary' => 52000.00,
                'joining_date' => '2012-06-15',

                'qualification' => 'B.Ed.',
                'user_id' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'avatar' => null,
                'prefix' => 'Mr.',
                'first_name' => 'Hari',
                'middle_name' => 'Bahadur',
                'last_name' => 'Thapa',
                'gender' => 'male',
                'date_of_birth' => '1978-11-30',
                'nid' => '1122334455',
                'contact' => '+9779823456789',
                'personal_email' => 'teacher3@example.com',
                'address' => 'Biratnagar',
                'city' => 'Biratnagar',
                'country' => 'Nepal',
                'postal_code' => '56600',
                'salary' => 54000.00,
                'joining_date' => '2008-09-01',

                'qualification' => 'M.Sc.',
                'user_id' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'avatar' => null,
                'prefix' => 'Mrs.',
                'first_name' => 'Anita',
                'middle_name' => 'Devi',
                'last_name' => 'Khatri',
                'gender' => 'female',
                'date_of_birth' => '1982-07-10',
                'nid' => '6677889900',
                'contact' => '+9779811122233',
                'personal_email' => 'teacher4@example.com',
                'address' => 'Lalitpur',
                'city' => 'Lalitpur',
                'country' => 'Nepal',
                'postal_code' => '44700',
                'salary' => 51000.00,
                'joining_date' => '2011-05-20',
                'qualification' => 'Ph.D.',

                'user_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'avatar' => null,
                'prefix' => 'Mr.',
                'first_name' => 'Nirajan',
                'middle_name' => null,
                'last_name' => 'Rana',
                'gender' => 'male',
                'date_of_birth' => '1975-03-22',
                'nid' => '5544332211',
                'contact' => '+9779809988776',
                'personal_email' => 'teacher5@example.com',
                'address' => 'Dharan',
                'city' => 'Dharan',
                'country' => 'Nepal',
                'postal_code' => '56700',
                'salary' => 53000.00,
                'joining_date' => '2009-11-15',
                'qualification' => 'M.A Sociology',

                'user_id' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'avatar' => null,
                'prefix' => 'Ms.',
                'first_name' => 'Kamala',
                'middle_name' => 'Devi',
                'last_name' => 'Magar',
                'gender' => 'female',
                'date_of_birth' => '1986-01-05',
                'nid' => '2233445566',
                'contact' => '+9779812233445',
                'personal_email' => 'teacher6@example.com',
                'address' => 'Bhaktapur',
                'city' => 'Bhaktapur',
                'country' => 'Nepal',
                'postal_code' => '44800',
                'salary' => 48000.00,
                'joining_date' => '2013-03-10',
                'qualification' => 'B.Ed.',

                'user_id' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'avatar' => null,
                'prefix' => 'Mr.',
                'first_name' => 'Ram',
                'middle_name' => 'Chandra',
                'last_name' => 'Karki',
                'gender' => 'male',
                'date_of_birth' => '1983-09-17',
                'nid' => '3344556677',
                'contact' => '+9779819988776',
                'personal_email' => 'teacher7@example.com',
                'address' => 'Janakpur',
                'city' => 'Janakpur',
                'country' => 'Nepal',
                'postal_code' => '45600',
                'salary' => 49000.00,
                'joining_date' => '2014-01-25',
                'qualification' => 'M.A History',

                'user_id' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'avatar' => null,
                'prefix' => 'Ms.',
                'first_name' => 'Maya',
                'middle_name' => null,
                'last_name' => 'Sharma',
                'gender' => 'female',
                'date_of_birth' => '1988-12-30',
                'nid' => '4455667788',
                'contact' => '+9779807766554',
                'personal_email' => 'teacher8@example.com',
                'address' => 'Nepalgunj',
                'city' => 'Nepalgunj',
                'country' => 'Nepal',
                'postal_code' => '21900',
                'salary' => 47000.00,
                'joining_date' => '2015-10-05',
                'qualification' => 'M.Sc. Physics',

                'user_id' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('teachers')->insert($teachers);
    }
}
